name: Godwoken Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  godwoken-tests:
    uses: classicalliu/godwoken-tests/.github/workflows/reusable-integration-test-v1.yml@add-kicker-repository-input
    with:
      web3_ref: "${{ github.sha }}"
      kicker_repository: "classicalliu/godwoken-kicker"
      kicker_ref: "for-refactor-db"
